// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Role 绑定的游戏角色。
 */
export interface Role {
    "roleId": string;
    "serverId": string;
    "roleName": string;
    "level": number;
    "areaName": string;
    "isDefault": boolean;
}

/**
 * SignInInfo 每日签到状态。
 */
export interface SignInInfo {
    "hadSignIn": boolean;
    "monthStart": string;
    "totalSignIn": number;
    "todayReward": string;
    "selectedDays": boolean[] | null;
}

/**
 * WidgetData 小组件数据（体力、宝箱等）。
 */
export interface WidgetData {
    "energy": {"cur": number, "max": number, "Full": string};
    "chest": number;
    "combat": string;
    "unlock": string;
    "battleExpire": string;
}
