// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * OverallStats 全账号统计。
 */
export interface OverallStats {
    "total": number;
    "count5": number;
    "count4": number;
    "avgPity": number;

    /**
     * 期望/实际，>1 偏欧 <1 偏非
     */
    "luckIndex": number;
    "pools": PoolStats[] | null;
}

/**
 * PoolStats 单卡池统计。
 */
export interface PoolStats {
    "poolType": number;
    "poolName": string;

    /**
     * 本窗口内记录数
     */
    "total": number;

    /**
     * 5★ 数量
     */
    "count5": number;

    /**
     * 4★ 数量
     */
    "count4": number;

    /**
     * 3★ 数量
     */
    "count3": number;

    /**
     * 平均出金抽数（0 表示样本不足）
     */
    "avgPity": number;

    /**
     * 当前已垫抽数
     */
    "pity": number;

    /**
     * true 表示窗口内无 5★，pity 为下界
     */
    "pityIsFloor": boolean;

    /**
     * 最近 5★ 名称
     */
    "last5Name": string;
    "last5Time": string;
}
