// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Character 角色条目（种子库最小字段集，待扩展）。
 */
export interface Character {
    "id": string;
    "name": string;
    "rarity": number;
    "element": string;
    "weapon": string;
}

/**
 * Echo 声骸条目：套装与主词条属性域。
 */
export interface Echo {
    "id": string;
    "name": string;
    "set": string;
    "cost": number;
    "main": string[] | null;
}

/**
 * EchoSubstat 声骸副词条定义（Max = 单词条满值）。
 */
export interface EchoSubstat {
    "name": string;
    "max": number;
}

/**
 * ScoreResult 声骸评分结果。
 */
export interface ScoreResult {
    /**
     * EquivalentRolls 权重内副词条的等效满-roll 词条数合计
     */
    "equivalentRolls": number;

    /**
     * Percent 评分百分比 = EquivalentRolls / 10 × 100（5 槽位 × 2 roll 满值）
     */
    "percent": number;
    "grade": string;
    "detail": ScoredSubstat[] | null;
    "unknown"?: string[] | null;
    "scheme": string;
}

/**
 * ScoreTables 声骸评分数据表。
 */
export interface ScoreTables {
    "substats": EchoSubstat[] | null;
    "schemes": WeightScheme[] | null;
}

/**
 * ScoredSubstat 评分明细。
 */
export interface ScoredSubstat {
    "name": string;
    "value": number;

    /**
     * 等效满-roll 词条数
     */
    "rolls": number;

    /**
     * 方案权重（0 表示不计分）
     */
    "weight": number;
}

/**
 * SubstatValue 一条副词条：名称与数值。
 */
export interface SubstatValue {
    "name": string;
    "value": number;
}

/**
 * WeightScheme 声骸评分权重方案。
 */
export interface WeightScheme {
    "name": string;
    "note": string;
    "ratio": { [_ in string]?: number } | null;
}
