// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Settings 应用设置。
 */
export interface Settings {
    /**
     * 开机自启
     */
    "autostart": boolean;

    /**
     * 每日自动签到
     */
    "signInAuto": boolean;

    /**
     * 自动签到时刻（0-23）
     */
    "signInHour": number;

    /**
     * 波片回满提醒
     */
    "waveNotify": boolean;

    /**
     * 手动指定的客户端日志路径
     */
    "logPath": string;

    /**
     * 界面语言（预留）
     */
    "language": string;
}
