// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * LogInfo 描述一个已发现的日志文件。
 */
export interface LogInfo {
    "path": string;
    "label": string;
}
