// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AppService 暴露给前端的应用级基础服务（版本信息等）。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

export function Platform(): $CancellablePromise<string> {
    return $Call.ByID(3813859089);
}

export function Version(): $CancellablePromise<string> {
    return $Call.ByID(1828333558);
}
