// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * GachaService 抽卡域对前端的唯一入口。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * DiscoverLogs 自动发现本机鸣潮客户端日志。
 */
export function DiscoverLogs(): $CancellablePromise<$models.LogCandidate[] | null> {
    return $Call.ByID(1471637431);
}

/**
 * ExportAccount 把账号数据导出为带时间戳的 JSON 文件，返回目标路径。
 */
export function ExportAccount(uid: string, destDir: string): $CancellablePromise<string> {
    return $Call.ByID(2916165732, uid, destDir);
}

/**
 * ImportAccount 从 JSON 文件导入账号数据（兼容 Mac 版 aMC 导出格式），返回 UID。
 */
export function ImportAccount(path: string): $CancellablePromise<string> {
    return $Call.ByID(753284001, path);
}

/**
 * ListAccounts 列出本地全部账号摘要。
 */
export function ListAccounts(): $CancellablePromise<$models.AccountSummary[] | null> {
    return $Call.ByID(1053800051);
}

/**
 * OpenAccount 打开指定账号的完整数据与统计。
 */
export function OpenAccount(uid: string): $CancellablePromise<$models.AccountDetail | null> {
    return $Call.ByID(4012298358, uid);
}

/**
 * Refresh 完整抓取流程：发现日志 → 提取 URL → 拉取全部卡池 → 合并 → 存储。
 * logPath 为空时走自动发现；playerID 为空时取日志中最近一条。
 */
export function Refresh(logPath: string, playerID: string): $CancellablePromise<$models.AccountDetail | null> {
    return $Call.ByID(2947236114, logPath, playerID);
}
