// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * GameDataService 图鉴与声骸评分对前端的入口。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as gamedata$0 from "./internal/gamedata/models.js";

/**
 * Characters 角色列表（支持名称/属性/武器过滤）。
 */
export function Characters(keyword: string, element: string, weapon: string): $CancellablePromise<gamedata$0.Character[] | null> {
    return $Call.ByID(1600662559, keyword, element, weapon);
}

/**
 * EchoScoreMeta 声骸评分元数据：词条满值表 + 权重方案 + 声骸列表。
 */
export function EchoScoreMeta(): $CancellablePromise<[gamedata$0.ScoreTables, gamedata$0.Echo[] | null]> {
    return $Call.ByID(432620129);
}

/**
 * ScoreEcho 声骸评分。
 */
export function ScoreEcho(scheme: string, subs: gamedata$0.SubstatValue[] | null): $CancellablePromise<gamedata$0.ScoreResult> {
    return $Call.ByID(3647776154, scheme, subs);
}
