// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * KurobbsService 账号域对前端的入口。
 * 模式说明：mock（默认，演示数据）/ real（真实库街区接口，⏸ 待真人测试短信登录）。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetOverview 账号中心聚合数据（未绑定时仅返回状态）。
 */
export function GetOverview(): $CancellablePromise<$models.KurobbsOverview | null> {
    return $Call.ByID(1969794256);
}

/**
 * GetStatus 当前绑定状态。
 */
export function GetStatus(): $CancellablePromise<$models.KurobbsStatus | null> {
    return $Call.ByID(3786783745);
}

/**
 * Login 使用手机号 + 验证码绑定库街区账号。
 */
export function Login(phone: string, code: string): $CancellablePromise<$models.KurobbsStatus | null> {
    return $Call.ByID(627192818, phone, code);
}

/**
 * Logout 解绑账号（清除本地凭证）。
 */
export function Logout(): $CancellablePromise<void> {
    return $Call.ByID(4219965355);
}

/**
 * SendSms 向手机号发送验证码。
 */
export function SendSms(phone: string): $CancellablePromise<void> {
    return $Call.ByID(1561190648, phone);
}

/**
 * SignInNow 对默认角色执行今日签到。
 */
export function SignInNow(): $CancellablePromise<string> {
    return $Call.ByID(3750639125);
}
