// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as gacha$0 from "./internal/gacha/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as kurobbs$0 from "./internal/kurobbs/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as wulog$0 from "./internal/wulog/models.js";

/**
 * AccountDetail 打开的账号详情。
 */
export interface AccountDetail {
    "uid": string;
    "svrArea": string;
    "fetchedAt": string;
    "stats": gacha$0.OverallStats;
    "dist": { [_ in string]?: number[] | null } | null;
    "recent5": RecentItem[] | null;
}

/**
 * AccountSummary 账号列表项。
 */
export interface AccountSummary {
    "uid": string;
    "svrArea": string;
    "fetchedAt": string;
    "total": number;
    "count5": number;
    "avgPity": number;
}

/**
 * KurobbsOverview 账号中心页聚合数据。
 */
export interface KurobbsOverview {
    "status": KurobbsStatus;
    "roles": kurobbs$0.Role[] | null;
    "signIn": kurobbs$0.SignInInfo | null;
    "widget": kurobbs$0.WidgetData | null;
}

/**
 * KurobbsStatus 登录状态概览。
 */
export interface KurobbsStatus {
    "bound": boolean;
    "name": string;
    "phone": string;
    "mode": string;
    "userId": string;
}

/**
 * LogCandidate 日志候选（供前端展示发现结果）。
 */
export type LogCandidate = wulog$0.LogInfo;

/**
 * RecentItem 最近 5★ 列表项；Gap 为与上一个 5★ 的间隔（-1 表示窗口内无前序 5★）。
 */
export interface RecentItem {
    "cardPoolType": string;
    "resourceId": number;
    "qualityLevel": number;
    "resourceType": string;
    "name": string;
    "count": number;
    "time": string;
    "pool": string;
    "gap": number;
}
