// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * NewsService 资讯与兑换码对前端的入口。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as kurobbs$0 from "./internal/kurobbs/models.js";

/**
 * Codes 兑换码列表。
 */
export function Codes(): $CancellablePromise<kurobbs$0.RedeemCode[] | null> {
    return $Call.ByID(2219620648);
}

/**
 * News 资讯列表（已绑定账号且真实模式时走官方接口，否则演示数据）。
 */
export function News(limit: number): $CancellablePromise<kurobbs$0.ForumPost[] | null> {
    return $Call.ByID(3528541673, limit);
}
